version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
      # - ./front:/home/user/web/front/
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
  front:
    build:
      context: ./dona-front/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
      # - ./front:/home/user/web/front/
    ports:
      - 80:80
    depends_on:
#      - front
      - app
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

volumes:
  postgres_data:
  static_volume:
  media_volume:
