# Generated by Django 4.0 on 2022-01-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('product', 'basket')},
        ),
    ]
