# Generated by Django 4.0 on 2022-01-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bonus'),
        ('product', '0007_productrating_productcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
    ]
