# Generated by Django 3.2.8 on 2022-01-10 11:34

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productcomment_created_at_productrating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(default='media/default-photo.jpg', upload_to=product.models.product_image_file_path),
        ),
    ]
