# Generated by Django 3.2.8 on 2022-01-27 06:04

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=product.models.category_image_file_path),
        ),
    ]
