# Generated by Django 3.2.8 on 2022-01-27 15:17

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=product.models.brand_image_file_path),
        ),
    ]
