# Generated by Django 3.2.8 on 2022-01-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_famous',
            field=models.BooleanField(default=False),
        ),
    ]
