# Generated by Django 3.2.8 on 2022-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('-id',)},
        ),
    ]
