# Generated by Django 3.2.8 on 2022-07-28 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_basketitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
