# Generated by Django 4.0 on 2021-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
