# Generated by Django 3.2.8 on 2022-01-22 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='901234567 holatda kiriting', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='901234567 holatda kiriting', regex='^(\\+998)\\d{9}$')], verbose_name='Telefon raqami'),
        ),
    ]
