# Generated by Django 3.2.8 on 2022-01-22 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='998901234567 holatda kiriting', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='998901234567 holatda kiriting', regex='^(998)\\d{9}$')], verbose_name='Telefon raqami'),
        ),
    ]
