# Generated by Django 3.2.8 on 2022-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_callbackrequest'),
        ('user', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to='product.Product'),
        ),
    ]
